### ISSUE TITLE
Issue 24_Os campos Levantamento, Desenvolvimento e homologação não permitem informar um valor menor

### ISSUE THREAD

**Issue by vloliveira1** [lucasbiel7/ProductionManager#24]
Os campos Levantamento, Desenvolvimento e homologação não permitem informar um valor menor.

Qualquer dúvida estou a disposição.

**Comment by Khoiti** [comment]
Esta regra é assim mesmo, pois o progresso só aumenta, caso tenha que diminuir só com a alteração de escopo
